[versions]
androidColorpickerpreference = "1.2.1"
espressoCore = "3.7.0"
gridlayout = "1.1.0"
junitKtx = "1.3.0"
kotestAssertionsCore = "6.2.4"
kotlin = "2.4.10"
material = "1.14.0"
opencv = "5.0.0.1"
preference = "1.2.1"
tensorflowLite = "2.17.0"

[libraries]
android-colorpickerpreference = { group = "com.github.attenzione", name = "android-ColorPickerPreference", version.ref = "androidColorpickerpreference" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
gridlayout = { group = "androidx.gridlayout", name = "gridlayout", version.ref = "gridlayout" }
junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitKtx" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotestAssertionsCore" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-test-junit5 = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5", version.ref = "kotlin" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
opencv = { group = "org.opencv", name = "opencv", version.ref = "opencv" }
preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
tensorflow-lite = { group = "org.tensorflow", name = "tensorflow-lite", version.ref = "tensorflowLite" }
